#! /bin/sh
# Creates cscope.files for use with cscope
# from the Linux Kernel source files.
# Written by Guenther Brunthaler in 2007.


LNX=/usr/src/linux


printf "%s\n" "-k -q" > cscope.files
find -H "$LNX" \
	\( \
		\( \
			-false \
			-o -path "$LNX/arch/*" ! -path "$LNX/arch/i[3-6]86*" \
			-o -path "$LNX/drivers/macintosh/*" \
			-o -path "$LNX/drivers/s390/*" \
			-o -path "$LNX/include/asm-*" ! -path "$LNX/include/asm-i[3-6]86*" \
			-o -path "$LNX/scripts/*" \
			-o -path "$LNX/sound/ppc/*" \
			-o -path "$LNX/tmp/*" \
			-o -path "$LNX/Documentation/*" \
		\) \
		-prune \
	\) -o \( \
		\( \
			-false \
			-o -name "Kconfig" \
			-o -name "*.[chxslyS]" \
		\) \
		-print \
	\) \
>> cscope.files
cscope -uv
