# Create a bunch of random files containing random bytes.
# $Id: /caches/xsvn/admdevel/trunk/prj/shared_bin_in_path_9wewpie7d5tawvtr9qf842c1z/mkrndfiles.pl 11 2006-11-06T23:14:31.537884Z root(xternal)  $


use strict;
use Getopt::Long;
my($opt_help, $opt_verbose);
my $Usage= <<"END";
$0 - create a set of random data files

Usage: $0 [ options ]

options supported:
-o <pattern>, --output <pattern>:
   A pathname optionally containing a substring of wildcard chararacters ('?'). 
   When the output files are created, the wildcard substring will be replaced 
   by a counter value. The value will have at least the same length as the 
   wildcard string, filling with leading '0' digits as required. If <pattern> 
   does not contain any wildcard string, the value will be appended to the end 
   of the basename (before any file extension).
-n <integer>, --numfiles <integer>:
   Specify the number of files to generate.
   This option may be subject to one of the count-modifiers (see below).
-s <integer>, --sizes <integer>:
   Specifies the number of bytes for each of the files.
   This option may be subject to one of the count-modifiers (see below).
--min <integer>:
   Modifies the next single modifyable option that specifies some count value. 
   The value specified for the --min option will then specify the minimum 
   allowed value for the count, and the modified option will specify the 
   maximum value. A random value in the resulting range will then be used as 
   the actual count value.
--median <integer>:
   Modifies the next single modifyable option that specifies some count value. 
   Requires the --min option also to be present. The random count value will be 
   generated within the specified range, and the value of the modified option 
   will specify the median value for the numbers to be generated; i. e. the 
   likelihood that a generated count value is lower than the median is the same 
   as the likelihood that the value is higher than the median.
--total <integer>:
   Modifies the next single modifyable option that specifies some count value. 
   It restricts the sum of the values generated by the modified option to be 
   the specified integer.
   For instance,
       --numfiles 2 --total 20 --min 5 --sizes 15
   will generate 2 files with individual sizes from 5 to 15 bytes, but the sum 
   of the sizes must be equal to 20.
   Possible results may be 5 and 15, 12 and 8, 14 and 6.
   This option may itself be subject to the other count-modifiers, e. g.
       --numfiles 2 --min 20 --total 30 --min 5 --sizes 15
   means that the sum of the lengths of the 2 generates files must equal some
   value between 20 and 30.
   For this reason, --total must precede other option modifiers that are 
   intended to modify the actual modifyable option rather than the argument of 
   --total itself.
-seed <integer>: Each integer creates a repeatable random sequence used to 
                 generate the files and their content. That is, the same files 
                 can be regenerated by using the identical options again. If 
                 this parameter is not specified, a non-repeatable random 
                 sequence is used by default.
-h, --help: Display this help.
-v, --verbose: Display messages while processing.

$0 has been written in 2003 by Guenther Brunthaler
END
Getopt::Long::Configure('bundling');
GetOptions(
 'h|help' => \$opt_help
 , 'v|verbose' => \$opt_verbose
) or die $Usage;
if ($opt_help) {
 print $Usage;
 exit;
}
